//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.JsonResources", typeof(JsonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;__v&quot;:9,&quot;_id&quot;:&quot;5414b8b3f8e1d50b0016b0c1&quot;,&quot;accessToken&quot;:&quot;887393c64ca993c34efc5c095d64f6b6&quot;,&quot;dob&quot;:&quot;2014-08-13T00:00:00.000Z&quot;,&quot;email&quot;:&quot;&quot;,&quot;lastLogin&quot;:&quot;2014-09-15T06:12:08.773Z&quot;,&quot;name&quot;:&quot;andrei talantsy&quot;,&quot;password&quot;:&quot;talanta&quot;,&quot;phone&quot;:&quot;+33669081609&quot;,&quot;username&quot;:&quot;talanta3&quot;,&quot;Whistles&quot;:[{&quot;_id&quot;:&quot;5414bd88f8e1d50b0016b0c8&quot;,&quot;provider&quot;:false,&quot;public&quot;:true,&quot;comment&quot;:&quot;test&quot;,&quot;type&quot;:&quot;MINI_BUS&quot;,&quot;size&quot;:[2,3],&quot;connections&quot;:[]},{&quot;_id&quot;:&quot;5414be6ff8e1d50b0016b0c9&quot;,&quot;provider&quot;:false,&quot;public&quot;:true,&quot;comment&quot;:&quot;test&quot;,&quot;type&quot;:&quot;MINI_BUS&quot;,&quot;siz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitFromBundle_complete {
            get {
                return ResourceManager.GetString("InitFromBundle_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 887393c64ca993c34efc5c095d64f6b6.
        /// </summary>
        internal static string InitFromBundle_complete_token {
            get {
                return ResourceManager.GetString("InitFromBundle_complete_token", resourceCulture);
            }
        }
    }
}
