#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Whistle.Droid.Resource", IsApplication=true)]

namespace Whistle.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SlidingMenuSharp.Resource.Attribute.behindOffset = global::Whistle.Droid.Resource.Attribute.behindOffset;
			global::SlidingMenuSharp.Resource.Attribute.behindScrollScale = global::Whistle.Droid.Resource.Attribute.behindScrollScale;
			global::SlidingMenuSharp.Resource.Attribute.behindWidth = global::Whistle.Droid.Resource.Attribute.behindWidth;
			global::SlidingMenuSharp.Resource.Attribute.fadeDegree = global::Whistle.Droid.Resource.Attribute.fadeDegree;
			global::SlidingMenuSharp.Resource.Attribute.fadeEnabled = global::Whistle.Droid.Resource.Attribute.fadeEnabled;
			global::SlidingMenuSharp.Resource.Attribute.mode = global::Whistle.Droid.Resource.Attribute.mode;
			global::SlidingMenuSharp.Resource.Attribute.selectorDrawable = global::Whistle.Droid.Resource.Attribute.selectorDrawable;
			global::SlidingMenuSharp.Resource.Attribute.selectorEnabled = global::Whistle.Droid.Resource.Attribute.selectorEnabled;
			global::SlidingMenuSharp.Resource.Attribute.shadowDrawable = global::Whistle.Droid.Resource.Attribute.shadowDrawable;
			global::SlidingMenuSharp.Resource.Attribute.shadowWidth = global::Whistle.Droid.Resource.Attribute.shadowWidth;
			global::SlidingMenuSharp.Resource.Attribute.touchModeAbove = global::Whistle.Droid.Resource.Attribute.touchModeAbove;
			global::SlidingMenuSharp.Resource.Attribute.touchModeBehind = global::Whistle.Droid.Resource.Attribute.touchModeBehind;
			global::SlidingMenuSharp.Resource.Attribute.viewAbove = global::Whistle.Droid.Resource.Attribute.viewAbove;
			global::SlidingMenuSharp.Resource.Attribute.viewBehind = global::Whistle.Droid.Resource.Attribute.viewBehind;
			global::SlidingMenuSharp.Resource.Id.fullscreen = global::Whistle.Droid.Resource.Id.fullscreen;
			global::SlidingMenuSharp.Resource.Id.left = global::Whistle.Droid.Resource.Id.left;
			global::SlidingMenuSharp.Resource.Id.margin = global::Whistle.Droid.Resource.Id.margin;
			global::SlidingMenuSharp.Resource.Id.right = global::Whistle.Droid.Resource.Id.right;
			global::SlidingMenuSharp.Resource.Id.selected_view = global::Whistle.Droid.Resource.Id.selected_view;
			global::SlidingMenuSharp.Resource.Id.slidingmenumain = global::Whistle.Droid.Resource.Id.slidingmenumain;
			global::SlidingMenuSharp.Resource.Layout.slidingmenumain = global::Whistle.Droid.Resource.Layout.slidingmenumain;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu = global::Whistle.Droid.Resource.Styleable.SlidingMenu;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = global::Whistle.Droid.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = global::Whistle.Droid.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = global::Whistle.Droid.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = global::Whistle.Droid.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = global::Whistle.Droid.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = global::Whistle.Droid.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = global::Whistle.Droid.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = global::Whistle.Droid.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = global::Whistle.Droid.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = global::Whistle.Droid.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = global::Whistle.Droid.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = global::Whistle.Droid.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = global::Whistle.Droid.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = global::Whistle.Droid.Resource.Styleable.SlidingMenu_viewBehind;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int add_to_basket_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int basket_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int enter = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int exit = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int product_detail_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int product_detail_out = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int btn_corner_radius = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int list_padding = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int shadow_width = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int slidingmenu_offset = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about_white_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int favorites_white_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int heart_small_green_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int howitworks_white_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int main_menu_bg_img = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int male_white_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int options_green_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int options_grey_icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int options_white_icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int profile_green_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int settings_white_icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int shadow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int signout_white_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int whistle_logo_green = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int whistle_white_icon = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001b
			public const int Badge = 2131034139;
			
			// aapt resource value: 0x7f05000c
			public const int FlyOutMenu = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int MenuFrame = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int Title = 2131034138;
			
			// aapt resource value: 0x7f050009
			public const int btnRegister = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int btnSignIn = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int contentArea = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int fullscreen = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int imageView1 = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int imageView2 = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int imgView = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int left = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout1 = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout2 = 2131034131;
			
			// aapt resource value: 0x7f050019
			public const int linearLayout3 = 2131034137;
			
			// aapt resource value: 0x7f050002
			public const int margin = 2131034114;
			
			// aapt resource value: 0x7f050018
			public const int menuIcon = 2131034136;
			
			// aapt resource value: 0x7f050001
			public const int right = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int selected_view = 2131034116;
			
			// aapt resource value: 0x7f05001c
			public const int slidingmenumain = 2131034140;
			
			// aapt resource value: 0x7f05000d
			public const int textView1 = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int textView2 = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int textView3 = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int txtWhistleMessage = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int txtWhistleMessage1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int txtWhistleMessage2 = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int view1 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int view2 = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int view3 = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int num_cols = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Landing = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MenuHolder = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MenuItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Registration = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int slidingmenumain = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int XamActionBarStyle = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int XamActionBarTheme = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int XamButton = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int XamSubtitleText = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int XamTitleText = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
